### PR TITLE
Fix OID Updates

### PR DESCRIPTION
**Pull request by theAvocadoCoder**
This addresses [issue 55](https://github.com/agile-learning-institute/mentorHub-person-api/issues/55#issue-2165470737)

### CODE REVIEW

**Review by FlatBallFlyer — CHANGES_REQUESTED** [review]
So does this mean I can only update these values, and I cannot provide them when adding a new record?

**Comment by theAvocadoCoder** [comment]
Yes, ommitting them in the request works and a request with only one or both of them also works

**Comment by FlatBallFlyer** [comment]
I think you misunderstood my question - will the post /person (new person) endpoint work if I specify id values there. I think you need to abstract this functionality and implement it in both the update and create actions.

**Comment by theAvocadoCoder** [comment]
Oh I see, I only implemented it for patch
I'll fix that now

**Review by FlatBallFlyer — APPROVED** [review]
Looks great!

**Pull request merged**
